### ISSUE TITLE
LoopsShouldNotBeInfiniteCheck: infinite loop

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-javascript#624]
```javascript
function foo() {
    for (let x=0 ; ; ) {       // makes rule to run infinitely
    }
}
```

**Comment by inverno** [comment]
Had a look into this, the source of the problem is the CFG. In `JsCfgBlock` we have the following code :
:
```
  JsCfgBlock skipEmptyBlocks() {
    JsCfgBlock block = this;
    while (block.successors().size() == 1 && block.elements().isEmpty()) {
      block = (JsCfgBlock) block.successors().iterator().next();
    }
    return block;
  }
```
This will be an infinite loop if the block is part of a loop of blocks (which is the case with infinite loops) and each block in that loop has zero elements (as it is the case for an empty for loop with no condition and no update expression).

The reason why this happens only when an initializer is present is because in `ControlFlowGraphBuilder.visitForStatement` when the initializer is empty, as well as the condition and the loop body, we add the `for` keyword as an element in the loop body block, thus accidentally avoiding the infinite loop.
```
    if (tree.init() != null) {
      buildExpression(tree.init());
    } else if (tree.condition() == null && loopBodyBlock.elements().isEmpty()) {
      loopBodyBlock.addElement(tree.forKeyword());
    }
```
We probably need to make this second part more coherent along with the actual fix in `JsCfgBlock`.
