### ISSUE TITLE
[feature request] import reports from eslint

### ISSUE THREAD

**Issue by gucong3000** [SonarSource/sonar-javascript#726]
**I want to request a feature.**

In the JS community, [ESLint](https://eslint.org/) is the most popular linter, and I don't think defining rules in this tool is the right thing to do. Direct import of Eslint report, for JS developers to be more friendly, but also effectively reduce the cost of this plugin maintenance rules

**SonarJS version:** Current
**SonarQube version:** Current
**SonarLint version:** Current

**Comment by gucong3000** [comment]
Another plugin has a similar plan but I'm not sure that way better.
https://github.com/groupe-sii/sonar-web-frontend-plugin/issues/4

**Comment by gucong3000** [comment]
This is the other two popular linter:
[Standard](https://github.com/emgeee/gulp-standard)
[XO](https://github.com/sindresorhus/gulp-xo)

**Comment by vilchik-elena** [comment]
@gucong3000 In fact, if you want to use EsLint in SQ there are some community plugins (e.g. this one https://github.com/sleroy/SonarEsLintPlugin).
We are aware of this need for the users, but we are not sure which strategy to take yet.

**Comment by gucong3000** [comment]
@vilchik-elena 
I'm a typical JavaScript programmer.
I was involved in the development of Eclint, Stylelint, I am eslint heavy users. 
What I need is an open generic error report uploads interface. Instead of a sealed box that encapsulates everything

**Comment by gucong3000** [comment]
I'm sorry to request this feature here, but your organization shut down all the other ways it.

**Comment by gucong3000** [comment]
> We are aware of this need for the users, but we are not sure which strategy to take yet.

Can you join me in the discussion?

**Comment by inverno** [comment]
Hi @gucong3000 I think that here is perfectly fine to have a discussion, but you raise many points and I'll first try to contact you directly so that we can have a more speedy conversation over chat or voice.

**Comment by gucong3000** [comment]
Thanks, All I need an interface to import generic lint results, just like coverage results import

**Comment by gucong3000** [comment]
I think JavaScript developers will not like `Sonar` to "analyzing" Their code. they prefer linters (ESLint, TSLint, Standard...) to do it. Sonar shouldn't be doing what not good at.

**Comment by inverno** [comment]
@gucong3000, I'll forget for a moment the tone of your messages so far and answer to your questions, rather than your presumptousness.

I of course disagree with you on Sonar not being good at static analysis (I presume you mean SonarJS and not SonarQube, otherwise you are mixing an analyzer with a code quality platform), it's in fact much more advanced than your average linter.
The fact is that SonarJS and ESLint are good at different things right now: ESLint is a very extensible analyzer, it has good integration with the JS ecosystem and great support for best-practices and style-related rules over multiple frameworks (especially thanks to its extensibility), on the other hand SonarJS is much better at finding [non-trivial problems in your code](https://sonarcloud.io/project/issues?id=org.eclipse.hudson%3Ahudson-parent&issues=AVPygfIvZ7GomVM6rJUe&open=AVPygfIvZ7GomVM6rJUe) (you'll notice that it takes time, even when pointed to it, to find out why the `notxml` variable will always be true in that condition). This is because we invested heavily in developing the underlying code models, which is not unique, but pretty rare.

Then, here is a very good place to request features for SonarJS, if you want to request features for SonarQube you can go to the [sonarqube google group](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/sonarqube). I don't get why you say that 'our organization' shut down ways for you to request features.

Finally, I don't get the reason for your rant in the first place : @vilchik-elena pointed you to a SonarQube plugin that allows you to do exactly what you seem to want to do (import an eslint report). Did you at least try it? I suggest you do, and I also suggest that maybe you give a try to SonarJS, especially using it in SonarLint and keeping the default, very low noise profile that focuses on bug-finding.

**Comment by gucong3000** [comment]
Please ignore my tone and all the information you see comes from Bing translation

**Comment by gucong3000** [comment]
The biggest problem with machine translation is that it doesn't respond correctly, and if that makes two angry, I should apologize for it

**Comment by gucong3000** [comment]
What I'm doing is not going to be one of my projects, using sonar to analyze the project, what I'm going to do is a middleware to report the various lint results in the front-end ecology to sonar
https://github.com/gucong3000/gulp-reporter

**Comment by gucong3000** [comment]
Let Java developers developed tools, to analyze the work of JS developers, it is difficult to poke their pain points, will be wasted
I think the reasonable solution should be to allow users to use the tools they are familiar with. Allow users to submit their own reports to sonar

**Comment by gucong3000** [comment]
No one can develop a universal tool unless the tool is like a Lego building block that can be replaced with random parts
SonarJS can't please everyone at the same time unless grammar analysis engine is free to replace it. Rules can be configured arbitrarily

**Comment by gucong3000** [comment]
I'm still looking for ways to import existing linting results.

**Comment by inverno** [comment]
@gucong3000 did you try https://github.com/sleroy/SonarEsLintPlugin ?

**Comment by gucong3000** [comment]
No. I just read the code and document.
Just the same name, is passionate not based on ESlint, just partial rules compatible with ESlint.

**Comment by gucong3000** [comment]
Linting tools I'd like to compatible.
CSSLint EditorConfig ESLint HTMLHint JSCS JSHint stylelint Standard TSLint XO

I'm trying to put the results of these linting tools in a [common file format](https://github.com/groupe-sii/sonar-web-frontend-plugin/files/1275978/lint-reports.zip).

**Comment by gucong3000** [comment]
Also, I forgot one thing, I am using SonarCloud with Travis CI. I don't have permission to install `SonarEsLintPlugin`
