### ISSUE TITLE
Unit test result does not show on SonarQube Dashboard for nodejs 

### ISSUE THREAD

**Issue by SudeepParajuli** [SonarSource/sonar-javascript#751]
**SonarQube Version** :   6.0.0 
**SonarJS:**  2.17.0.3154

**Issue** 

The main aim is to display coverage report and the unit test result in SonarQube dashboard. Though I am able to get the coverage report but not able to get the unit test result in SonarQube dashboard . 
I have been using the mocha for unit testing and istanbul nyc for code coverage. The report generated by mocha is in xml format using the package **mocha-sonar-reporter** and the coverage report is in lcov format . 

_**Sonar.Property File** 

sonar.projectKey=unittest
sonar.projectName=unittest
sonar.projectVersion=1.0.0

sonar.sources=src/
sonar.tests=test/

sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.javascript.jstestdriver.reportsPath=/home/jenkinsbot/workspace/devops_stuffs/reports
sonar.javascript.lcov.reportPath=/home/jenkinsbot/workspace/devops_stuffs/reports/lcov.info_

**SonarQube log** : 

_[Pipeline] wrap
Injecting SonarQube environment variables using the configuration: Sonar(dk.147)
[Pipeline] {
[Pipeline] sh
[e_feature_COS-239-unit-test-P23YKERWYLNSD6K3ISKUHA5NSJTRN6K7DRJGKI5QLG6LTD3HHOPA] Running shell script
+ /home/jenkinsbot/sonar-scanner-2.9.0.670/bin/sonar-scanner
INFO: Scanner configuration file: /home/jenkinsbot/sonar-scanner-2.9.0.670/conf/sonar-scanner.properties
INFO: Project root configuration file: /home/jenkinsbot/workspace//sonar-project.properties
INFO: SonarQube Scanner 2.9.0.670
INFO: Java 1.8.0_131 Oracle Corporation (64-bit)
INFO: Linux 4.4.0-92-generic amd64
INFO: User cache: /home/jenkinsbot/.sonar/cache
INFO: Load global repositories
INFO: Load global repositories (done) | time=94ms
INFO: User cache: /home/jenkinsbot/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=4ms
INFO: SonarQube server 6.0
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=100ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=17ms
INFO: Load active rules
INFO: Load active rules (done) | time=231ms
INFO: Publish mode
INFO: -------------  Scan cosmicunittest
INFO: Language is forced to js
INFO: Load server rules
INFO: Load server rules (done) | time=71ms
INFO: Base dir: /home/jenkinsbot/workspace/
INFO: Working dir: /home/jenkinsbot/workspace/eP23YKERWYLNSD6K3ISKUHA5NSJTRN6K7DRJGKI5QLG6LTD3HHOPA/.scannerwork
INFO: Source paths: src
INFO: Test paths: test
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: 152 files indexed
INFO: Quality profile for js: LogPoint Way
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=33ms
INFO: Sensor SCM Sensor
INFO: Sensor SCM Sensor (done) | time=20ms
INFO: Sensor JavaScript Squid Sensor
INFO: 138 source files to be analyzed
INFO: Unit Test Coverage Sensor is started
INFO: 138/138 source files have been analyzed
INFO: Analysing [/home/jenkinsbot/workspace/reports/lcov.info]
INFO: Integration Test Coverage Sensor is started
INFO: Overall Coverage Sensor is started
INFO: Analysing [/home/jenkinsbot/workspace/reports/lcov.info]
INFO: Sensor JavaScript Squid Sensor (done) | time=4852ms
INFO: Sensor XmlFileSensor
INFO: Sensor XmlFileSensor (done) | time=1ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=76ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=3ms
INFO: Sensor CPD Block Indexer
INFO: DefaultCpdBlockIndexer is used for js
INFO: Sensor CPD Block Indexer (done) | time=1ms
INFO: Calculating CPD for 129 files
INFO: CPD calculation finished
INFO: Analysis report generated in 222ms, dir size=903 KB
INFO: Analysis reports compressed in 300ms, zip size=512 KB
INFO: Analysis report uploaded in 24ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://test/dashboard/index/unittest
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at test
INFO: Task total time: 7.649 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 8.784s
INFO: Final Memory: 61M/551M
INFO: ------------------------------------------------------------------------
[Pipeline] }
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: SUCCESS_

![screen shot 2017-09-20 at 11 33 39 am](https://user-images.githubusercontent.com/13688847/30628717-b7683888-9df7-11e7-8a76-cfce66fd5a62.png)

**Comment by vilchik-elena** [comment]
Hi,

Unit test results import is not provided anymore by SonarJS. For that you should use SQ's native feature [Generic Test Data](https://docs.sonarqube.org/display/SONAR/Generic+Test+Data) (since SQ 6.2). If you use SQ < 6.2 use this plugin https://docs.sonarqube.org/display/PLUG/Generic+Test+Coverage.

**Comment by SudeepParajuli** [comment]
Since my SQ < 6.2 I tried the Generic Test Coverage Plugin with the following changes :

Installed **Generic Coverage Plugin 1.2**
Edited the sonar.property file with : **sonar.genericcoverage.unitTestReportPaths=report**

Still I am not able to achieve the unit test result depiction on dashboard.

The XML generated by my mocha-sonar-reporter is in this format :

```
<testsuite name="Mocha Tests" tests="50" failures="0" errors="0" skipped="0" timestamp="Wed, 20 Sep 2017 04:00:45 GMT" time="3.933">
<testcase classname="app/redux/transaction.spec.js" name="Search actions creates LOCAL_FETCH_SUCCESS when translation fetch done" time="0.01"/>

```
But for Generic Coverage Plugin it should be in this format :

```
<unitTest version="1">
  <file path="src/test/java/com/example/MyTestClass.java">
    <testCase name="test1" duration="500"/>
     </testCase>
    </file>
</unitTest>
```
How could I generate the xml in this supported format with mocha . Any idea @vilchik-elena

**Comment by vilchik-elena** [comment]
try this https://github.com/pghalliday/mocha-sonar-reporter or this https://github.com/mageddo/mocha-sonar-generic-test-coverage

**Comment by SudeepParajuli** [comment]
So kind of you . Thank you @vilchik-elena . It worked .

**Comment by jithuvijayan1992** [comment]
@vilchik-elena my SQ's version is 6.4 , here i am using mocha for my nodjs project. The code coverage is not getting on the SQ's dashboard, which tool i need to use.

**Comment by vilchik-elena** [comment]
@jithuvijayan1992 create new ticket, put configuration and logs

**Comment by jithuvijayan1992** [comment]
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /home/jithu/Integragte/phoenix-notification-service/sonar-project.properties
INFO: SonarQube Scanner 3.1.0.1141
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.10.0-38-generic amd64
INFO: User cache: /home/jithu/.sonar/cache
INFO: SonarQube server 6.4.0
INFO: Default locale: "en_IN", source code encoding: "UTF-8"
INFO: Load global settings
INFO: Load global settings (done) | time=47ms
INFO: User cache: /home/jithu/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=14ms
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=67ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=75ms
INFO: Load active rules
INFO: Load active rules (done) | time=380ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=51ms
INFO: Publish mode
INFO: Project key: NotificationService
INFO: -------------  Scan Notification Service
INFO: Load server rules
INFO: Load server rules (done) | time=88ms
INFO: Language is forced to js
INFO: Initializer GenericCoverageSensor
INFO: Initializer GenericCoverageSensor (done) | time=0ms
INFO: Base dir: /home/jithu/Integragte/phoenix-notification-service
INFO: Working dir: /home/jithu/Integragte/phoenix-notification-service/.scannerwork
INFO: Source paths: core, config, migrations, mq
INFO: Test paths: test
INFO: Source encoding: UTF-8, default locale: en_IN
INFO: Index files
INFO: Excluded sources: 
INFO:   **/node_modules/**
WARN: File '/home/jithu/Integragte/phoenix-notification-service/config/database.json' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180528105103-phoenix-down.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180525105311-user-device-instance-up.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180601103757-create-activity-and-template-up.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180601103757-create-activity-and-template-down.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180525105311-user-device-instance-down.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180525103108-user-down.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180528105103-phoenix-up.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/migrations/sqls/20180525103108-user-up.sql' is ignored because it doesn't belong to the forced language 'js'
WARN: File '/home/jithu/Integragte/phoenix-notification-service/test/TEST-all.xml' is ignored because it doesn't belong to the forced language 'js'
INFO: 17 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for js: Sonar way Recommended
INFO: Sensor ZapSensor [zap]
WARN: ZAP report not found at target/zap-reports/zapReport.html
INFO: Sensor ZapSensor [zap] (done) | time=0ms
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=0ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=2ms
INFO: Sensor JavaScript Squid Sensor [javascript]
INFO: 14 source files to be analyzed
INFO: Unit Test Coverage Sensor is started
INFO: 14/14 source files have been analyzed
INFO: Integration Test Coverage Sensor is started
INFO: Overall Coverage Sensor is started
INFO: Sensor JavaScript Squid Sensor [javascript] (done) | time=994ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=42ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=0ms
INFO: Calculating CPD for 14 files
INFO: CPD calculation finished
INFO: Analysis report generated in 104ms, dir size=85 KB
INFO: Analysis reports compressed in 48ms, zip size=47 KB
INFO: Analysis report uploaded in 218ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/sonar/dashboard/index/NotificationService
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://localhost:9000/sonar/api/ce/task?id=AWPfbLtPTD4p2pXCensG
INFO: Task total time: 3.793 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 5.357s
INFO: Final Memory: 10M/244M
INFO: ------------------------------------------------------------------------
#################################################################

sonar-project.properties
----------------------------------
sonar.projectKey=NotificationService
sonar.projectName=Notification Service
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=./core,./config,./migrations,./mq
sonar.language=js
sonar.javascript.file.suffixes=.js
sonar.javascript.environments=node,mocha
sonar.javascript.jstestdriver.reportsPath=./test/TEST-all.xml
sonar.tests=test
sonar.eslint.eslintconfigpath=eslintrc.json
sonar.exclusions=**/node_modules/**
-------------------------

**Comment by vilchik-elena** [comment]
jithuvijayan1992 create new ticket..

**Comment by kiransterling** [comment]
> So kind of you . Thank you @vilchik-elena . It worked .

Which one did you used ?
